# Generated by Django 3.2.9 on 2021-11-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='job',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
