# Generated by Django 3.2.9 on 2021-11-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211116_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='job',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
