# Generated by Django 3.2.9 on 2021-11-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20211116_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('location', models.ImageField(height_field=100, upload_to='static/images/locations', width_field=200)),
                ('population', models.PositiveIntegerField()),
            ],
        ),
    ]
