# Generated by Django 3.2.9 on 2021-11-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Ville',
        ),
    ]
