# Generated by Django 3.2.9 on 2021-11-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_rename_city_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('superficie', models.FloatField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='job',
            new_name='emploi',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='tel',
        ),
        migrations.RenameField(
            model_name='ville',
            old_name='name',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='ville',
            name='location',
        ),
        migrations.AddField(
            model_name='contact',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='localisation',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='static/images/locations', width_field=200),
        ),
    ]
